### ISSUE TITLE
maintain a changelog

### ISSUE THREAD

**Issue by faassen** [faassen/reselect#14]
We should maintain some kind of changelog so people can see what's new in releases. I usually just maintain a CHANGES document and make sure to update it each time there's a change, but perhaps there are other ways -- what does Redux do, for instance?

**Comment by speedskater** [comment]
I usually add Changes to the bottom of the README. In case it becomes too long it could be moved to a separate file.

**Comment by ellbee** [comment]
A changelog has been added

**Comment by speedskater** [comment]
:+1:
