### ISSUE TITLE
Multiple @connect decorators?

### ISSUE THREAD

**Issue by eelkeh** [faassen/reselect#17]
Just asking, not sure about the best practice here. 
Say a component deep in the tree needs a derived or composed state, all the "main" stores are declared on the root component... is it considered good practice to add another `@connect` on the deep component, or should we pass the derived state down from the root component too?

**Comment by speedskater** [comment]
@eelkeh I think this depends on the goals you are trying to achieve.

If you add the main reducers to the top component. They will automatically trigger a rerender if your data changes. Hence you could as well pass your data down.

If some components in your hierarchy only depend on parts of the 'main' reducers I would suggest to add finer grained selectors on the root component and other connectors on the components deeper down. 

e.g. in case of a form depending on your data you could select the complete form data at the root of your compound form component or you could create selectors for each form field and the selector at the root level could completely be removed.

Was this answer helpful for you?

**Comment by ellbee** [comment]
I agree with @speedskater, it depends! 

I will add that I don't think using reselect means you should split your app into [smart and dumb](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) components any differently.

**Comment by ellbee** [comment]
[This page](http://rackt.github.io/redux/docs/basics/UsageWithReact.html) from the excellent Redux documentation addresses the issue, as does this Redux [issue](https://github.com/rackt/redux/issues/419).
