### ISSUE TITLE
Can't pass props in selectors

### ISSUE THREAD

**Issue by vasa-chi** [faassen/reselect#20]
`react-redux` supports [passing props to select](https://github.com/gaearon/react-redux/blob/master/src/components/createConnectDecorator.js#L18). Currently reselect only passes state. Is it possible to add props to selector functions?

**Comment by ellbee** [comment]
I'm not sure that the new react-redux api for the connect decorator is going to support this. [Check out this PR](https://github.com/gaearon/react-redux/pull/16)

**Comment by vasa-chi** [comment]
Huh. That would be unfortunate... Maybe @gaearon can clarify?

**Comment by vasa-chi** [comment]
Seems that there will be an additional argument for `@connect` decorator for using props to further filter the state. So I guess that yes, this api will get deprecated.

**Comment by ellbee** [comment]
Confirmed as gone in the [release notes for react-redux v.0.5.0](https://github.com/gaearon/react-redux/releases/tag/v0.5.0)

**Comment by scottcorgan** [comment]
It looks like this added back in react-redux. Can we get it back in this package?

**Comment by ellbee** [comment]
Yep, I guess we should look into this now

**Comment by scottcorgan** [comment]
Any time frame on this? Attempted to jump in on a fork, but didn't know if changes were coming soon for a 1.0.

**Comment by ellbee** [comment]
Funnily enough, I was just looking at it. Did you have a plan? I'm wondering whether the dumb default memoize and its reference equality is going to work with the props. I don't recall how the props are handled inside react. I guess if the prop object is mutative and has a stable reference for the lifetime of the component *or* it is recreated entirely on each render then we might have problems?

I think that the API might change slightly in the next version, possibly allowing the user to [specify a memoization function in createSelectorCreator](7) and allowing [variadic depencies](27). I just started exploring this in my fork [here](https://github.com/ellbee/reselect.git) if you'd like to have a look.

**Comment by gaearon** [comment]
>I guess if the prop object is mutative and has a stable reference for the lifetime of the component or it is recreated entirely on each render then we might have problems?

Props object is new every time. It's considered immutable.

**Comment by faassen** [comment]
Okay, I just finally started using reselect in a project and ran into this one. So basically we want to parameterize the select expression with an additional object that should be passed down the select chain, right? And we should be able to express when we consider this object unchanged, so that we can make use of caching.

**Comment by ellbee** [comment]
Take a look at #35. We've had a bit of a discussion about this there

**Comment by ellbee** [comment]
Address in the 1.0.0 release
