### ISSUE TITLE
Allow variadic dependencies as well as an array

### ISSUE THREAD

**Issue by ccapndave** [faassen/reselect#27]
As well as the current system of `createSelector([a, b, c], (a, b, c) => ...)` it would be great if it would also be possible to do `createSelector(a, b, c, (a, b, c) => ...)`

This would allow us to implement robust and strictly typed Typescript definitions on `createSelector`.

**Comment by ellbee** [comment]
Oh, very interesting. The issue is that all values in array have to have the same type?

**Comment by ccapndave** [comment]
Exactly (or you can specify a union type, but not the order they come in).  If they are separate arguments they can be individually typed.  This is how Rx gets such good typing in Typescript for functions such as `comineLatest`.

**Comment by ellbee** [comment]
Ok, thanks. I don't see why we shouldn't do this. @faassen?

**Comment by speedskater** [comment]
@ccapndave @ellbee Sounds interesting to me. 
I think it has two more advantages:
* it deals with a common mistake that array brackets are ommited.
* ommiting the array brackets makes it imho more readable.

**Comment by ellbee** [comment]
Variadic dependencies added to the 1.0.0 release
