### ISSUE TITLE
Explain that reselect does not depend on Redux

### ISSUE THREAD

**Issue by rwillrich** [faassen/reselect#30]
I have the need to use the concept of memoized selectors on an app using Facebook's Flux and as I'm following Redux and satellite projects I heard of reselect and find it to be a useful solution.

Maybe it would be nice if you explain that you do not need Redux to use reselect. What you guys think?

**Comment by ellbee** [comment]
Yes, sounds like a good idea. I've added it to the [list of improvements we are planning to make to the docs in the near future](https://github.com/faassen/reselect/issues/22).
