### ISSUE TITLE
Keep /src included in package.json

### ISSUE THREAD

**Issue by tgriesser** [faassen/reselect#41]
For folks who would like to install a specific version of the library from npm (I just tried installing the 1.0 alpha), since the `/lib` dir isn't compiled there doesn't seem to be anything to reference in the `node_modules` after it pulls from github.

Also worth considering, support the `jsnext:main` [field in package.json](https://github.com/rollup/rollup/wiki/ES6-modules#es6-friendly-libraries) so we can use tooling to target the ES6.

**Comment by ellbee** [comment]
Hey @tgriesser, thanks for the suggestions. Check out version 1.0.0-alpha2, they should be in there.

**Comment by ellbee** [comment]
Fixed in version 1.0.0
