### ISSUE TITLE
test coverage tool

### ISSUE THREAD

**Issue by faassen** [faassen/reselect#5]
Does anyone know a good test coverage tool? This way we can make sure we have full coverage of our code.

**Comment by ellbee** [comment]
Istanbul? https://github.com/gotwarlost/istanbul

**Comment by faassen** [comment]
I have absolutely no experience with coverage tools in the JS world yet, so Instanbul sounds fine to me. The most important thing is that it doesn't get confused by babel ES6 transpilation, I think.

**Comment by faassen** [comment]
Ahah: https://github.com/ambitioninc/babel-istanbul

**Comment by ellbee** [comment]
I copied the test coverage script from redux. Our current status:

=============================== Coverage summary ===============================
Statements   : 100% ( 35/35 ), 1 ignored
Branches     : 100% ( 8/8 ), 1 ignored
Functions    : 100% ( 11/11 )
Lines        : 100% ( 24/24 )
===============================================================================

**Comment by faassen** [comment]
Yay! I had to wipe my node_modules and do another npm install, but after that it all just worked.

We should document the basic commands we offer somewhere so that people know what's available.
